
spring:
  liquibase:
    url: jdbc:postgresql://localhost:5432/myBlogDatabase
    user: robi
    password: 1234
    change-log: classpath:liquibaseFiles/changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/myBlogDatabase
    username: robi
    password: 1234

  jpa:
    show-sql: true
    format_sql: true
    database:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 30m
